countries_to_visit = ['Japan', 'Iceland', 'Canada', 'New Zealand', 'Scotland']
print(countries_to_visit)
print(sorted(countries_to_visit))
print(countries_to_visit)
print(sorted(countries_to_visit, reverse = True))
print(countries_to_visit)
countries_to_visit.reverse()
print(countries_to_visit)
countries_to_visit.reverse()
print(countries_to_visit)
countries_to_visit.sort()
print(countries_to_visit)
countries_to_visit.sort(reverse = True)
print(countries_to_visit)
print(countries_to_visit[2])
